language: node_js
node_js:
  - "6"

install:
  - npm install

script:
  - npm run build

after_success:
  - cd dist ; cp -R ../docs/XYSY/images XYSY/images ; cp -R ../docs/XYTS/images XYTS/images ;
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages 	